baseURL = "https://www.kumbayops.com/"
languageCode = "en-us"
#defaultContentLanguage = "en"
title = "KumbayOps LLC"
enableRobotsTXT = true
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
  author = "KumbayOps LLC"
  #slogan = "Find Your Ops"